java_test(
    name = "AttestationApplicationIdTest",
    srcs = ["AttestationApplicationIdTest.java"],
    deps = [
        "//server/src/main/java/com/google/android/attestation",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk15on",
    ],
)

java_test(
    name = "AuthorizationListTest",
    srcs = ["AuthorizationListTest.java"],
    deps = [
        "//server/src/main/java/com/google/android/attestation",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk15on",
    ],
)

java_test(
    name = "ParsedAttestationRecordTest",
    srcs = ["ParsedAttestationRecordTest.java"],
    deps = [
        "//server/src/main/java/com/google/android/attestation",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk15on",
    ],
)

java_test(
    name = "RootOfTrustTest",
    srcs = ["RootOfTrustTest.java"],
    deps = [
        "//server/src/main/java/com/google/android/attestation",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk15on",
    ],
)
