java_binary(
    name = "KeyAttestationExample",
    srcs = ["KeyAttestationExample.java"],
    data = ["//server/examples:example_certificates"],
    deps = [
        "//server/src/main/java/com/google/android/attestation",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_javalite",
        "@maven//:org_bouncycastle_bcprov_jdk18on",
    ],
)
