java_binary(
    name = "KeyAttestationExample",
    srcs = ["KeyAttestationExample.java"],
    data = ["//src/test/resources:example_certificates"],
    deps = [
        "//src/main/java/com/google/android/attestation",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_javalite",
    ],
)
