java_test(
    name = "AttestationApplicationIdTest",
    srcs = ["AttestationApplicationIdTest.java"],
    deps = [
        "//src/main/java/com/google/android/attestation",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_javalite",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "AuthorizationListTest",
    srcs = ["AuthorizationListTest.java"],
    deps = [
        "//src/main/java/com/google/android/attestation",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk18on",
    ],
)

java_test(
    name = "ParsedAttestationRecordTest",
    srcs = ["ParsedAttestationRecordTest.java"],
    deps = [
        "//src/main/java/com/google/android/attestation",
        "@maven//:com_google_protobuf_protobuf_javalite",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk18on",
    ],
)

java_test(
    name = "RootOfTrustTest",
    srcs = ["RootOfTrustTest.java"],
    deps = [
        "//src/main/java/com/google/android/attestation",
        "@maven//:com_google_protobuf_protobuf_javalite",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_bouncycastle_bcprov_jdk18on",
    ],
)
